backend:
  name: git-gateway
  repo: BiigFish/alexis
  branch: main

publish_mode: editorial_workflow

media_folder: "src/img"
public_folder: "/img"

collections:
  - label: "Posts"
    name: "post"
    folder: "src/posts"
    create: true
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "string" }
      - { label: "Color", name: "color", widget: "color", enableAlpha: true, allowInput: true }
      - { label: "Text", name: "body", widget: "markdown" }
  - label: "About"
    name: "about"
    files:
      - label: "About"
        name: "about"
        file: "src/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - label: "About Image"
            name: "img"
            widget: "image"
            default: "/img/about.JPG"
          - { label: "Text", name: "body", widget: "markdown" }